# Generated by Django 5.2.3 on 2025-07-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musichall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresso',
            options={'managed': True},
        ),
    ]
