# Generated by Django 5.2.4 on 2025-07-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musichall', '0002_alter_ingresso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresso',
            options={'managed': False},
        ),
    ]
